<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Model" nsURI="dk.itu.model.featureModel" nsPrefix="model">
  <eClassifiers xsi:type="ecore:EClass" name="SolitaryFeature" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" lowerBound="1"
        eType="#//SolitaryType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1"
        eType="#//Group" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//SolitaryFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SimpleType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroupedFeature" eSuperTypes="#//Feature"/>
  <eClassifiers xsi:type="ecore:EEnum" name="SimpleType">
    <eLiterals name="boolean"/>
    <eLiterals name="int" value="1"/>
    <eLiterals name="double" value="2"/>
    <eLiterals name="String" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="RootFeature" upperBound="-1"
        eType="#//Feature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Group">
    <eStructuralFeatures xsi:type="ecore:EReference" name="groupedFeatures" lowerBound="2"
        upperBound="-1" eType="#//GroupedFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inclusive" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BinaryOperator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="BinaryOperator"/>
    </eAnnotations>
    <eLiterals name="Equals"/>
    <eLiterals name="Higher" value="1"/>
    <eLiterals name="Lower" value="2"/>
    <eLiterals name="And" value="3"/>
    <eLiterals name="Add" value="4"/>
    <eLiterals name="Subtract" value="5"/>
    <eLiterals name="Divide" value="6"/>
    <eLiterals name="Multiply" value="7"/>
    <eLiterals name="Or" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryOperation" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rexp" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lexp" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//BinaryOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryOperation" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//UnaryOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" lowerBound="1" eType="#//Expression"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="exp"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constant" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="NULL" eSuperTypes="#//Constant"/>
  <eClassifiers xsi:type="ecore:EClass" name="Number" eSuperTypes="#//Constant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identifier" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1" eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UnaryOperator">
    <eLiterals name="Not"/>
    <eLiterals name="Minus" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SolitaryType">
    <eLiterals name="Optional"/>
    <eLiterals name="Mandatory" value="1"/>
  </eClassifiers>
</ecore:EPackage>
