/**
 * generated by Xtext
 */
package org.xtext.example.mydsl1.serializer;

import org.xtext.example.mydsl1.serializer.AbstractMyDslSemanticSequencer;

@SuppressWarnings("all")
public class MyDslSemanticSequencer extends AbstractMyDslSemanticSequencer {
}
