/*
* generated by Xtext
*/
package org.xtext.example.mydsl1.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.example.mydsl1.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {
	
	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.example.mydsl1.ui.contentassist.antlr.internal.InternalMyDslParser createParser() {
		org.xtext.example.mydsl1.ui.contentassist.antlr.internal.InternalMyDslParser result = new org.xtext.example.mydsl1.ui.contentassist.antlr.internal.InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getFeatureAccess().getAlternatives(), "rule__Feature__Alternatives");
					put(grammarAccess.getExpressionAccess().getAlternatives(), "rule__Expression__Alternatives");
					put(grammarAccess.getSolitaryFeatureAccess().getAlternatives_3(), "rule__SolitaryFeature__Alternatives_3");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getGroupedFeatureAccess().getAlternatives_2(), "rule__GroupedFeature__Alternatives_2");
					put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
					put(grammarAccess.getBinaryOperatorAccess().getAlternatives(), "rule__BinaryOperator__Alternatives");
					put(grammarAccess.getUnaryOperatorAccess().getAlternatives(), "rule__UnaryOperator__Alternatives");
					put(grammarAccess.getSimpleTypeAccess().getAlternatives(), "rule__SimpleType__Alternatives");
					put(grammarAccess.getSolitaryTypeAccess().getAlternatives(), "rule__SolitaryType__Alternatives");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getModelAccess().getGroup_3(), "rule__Model__Group_3__0");
					put(grammarAccess.getModelAccess().getGroup_3_2(), "rule__Model__Group_3_2__0");
					put(grammarAccess.getSolitaryFeatureAccess().getGroup(), "rule__SolitaryFeature__Group__0");
					put(grammarAccess.getSolitaryFeatureAccess().getGroup_3_0(), "rule__SolitaryFeature__Group_3_0__0");
					put(grammarAccess.getSolitaryFeatureAccess().getGroup_3_0_1(), "rule__SolitaryFeature__Group_3_0_1__0");
					put(grammarAccess.getSolitaryFeatureAccess().getGroup_3_0_2(), "rule__SolitaryFeature__Group_3_0_2__0");
					put(grammarAccess.getSolitaryFeatureAccess().getGroup_3_0_3(), "rule__SolitaryFeature__Group_3_0_3__0");
					put(grammarAccess.getSolitaryFeatureAccess().getGroup_3_0_4(), "rule__SolitaryFeature__Group_3_0_4__0");
					put(grammarAccess.getSolitaryFeatureAccess().getGroup_3_0_4_2(), "rule__SolitaryFeature__Group_3_0_4_2__0");
					put(grammarAccess.getSolitaryFeatureAccess().getGroup_3_1(), "rule__SolitaryFeature__Group_3_1__0");
					put(grammarAccess.getGroupAccess().getGroup(), "rule__Group__Group__0");
					put(grammarAccess.getGroupedFeatureAccess().getGroup(), "rule__GroupedFeature__Group__0");
					put(grammarAccess.getGroupedFeatureAccess().getGroup_2_0(), "rule__GroupedFeature__Group_2_0__0");
					put(grammarAccess.getGroupedFeatureAccess().getGroup_2_0_1(), "rule__GroupedFeature__Group_2_0_1__0");
					put(grammarAccess.getGroupedFeatureAccess().getGroup_2_0_2(), "rule__GroupedFeature__Group_2_0_2__0");
					put(grammarAccess.getGroupedFeatureAccess().getGroup_2_0_2_3(), "rule__GroupedFeature__Group_2_0_2_3__0");
					put(grammarAccess.getGroupedFeatureAccess().getGroup_2_0_3(), "rule__GroupedFeature__Group_2_0_3__0");
					put(grammarAccess.getGroupedFeatureAccess().getGroup_2_0_3_1(), "rule__GroupedFeature__Group_2_0_3_1__0");
					put(grammarAccess.getGroupedFeatureAccess().getGroup_2_0_4(), "rule__GroupedFeature__Group_2_0_4__0");
					put(grammarAccess.getGroupedFeatureAccess().getGroup_2_0_4_3(), "rule__GroupedFeature__Group_2_0_4_3__0");
					put(grammarAccess.getGroupedFeatureAccess().getGroup_2_1(), "rule__GroupedFeature__Group_2_1__0");
					put(grammarAccess.getBinaryOperationAccess().getGroup(), "rule__BinaryOperation__Group__0");
					put(grammarAccess.getUnaryOperationAccess().getGroup(), "rule__UnaryOperation__Group__0");
					put(grammarAccess.getNULLAccess().getGroup(), "rule__NULL__Group__0");
					put(grammarAccess.getIdentifierAccess().getGroup(), "rule__Identifier__Group__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getModelAccess().getRootFeatureAssignment_3_1(), "rule__Model__RootFeatureAssignment_3_1");
					put(grammarAccess.getModelAccess().getRootFeatureAssignment_3_2_1(), "rule__Model__RootFeatureAssignment_3_2_1");
					put(grammarAccess.getSolitaryFeatureAccess().getRequiredAssignment_1(), "rule__SolitaryFeature__RequiredAssignment_1");
					put(grammarAccess.getSolitaryFeatureAccess().getNameAssignment_2(), "rule__SolitaryFeature__NameAssignment_2");
					put(grammarAccess.getSolitaryFeatureAccess().getTypeAssignment_3_0_1_1(), "rule__SolitaryFeature__TypeAssignment_3_0_1_1");
					put(grammarAccess.getSolitaryFeatureAccess().getGroupsAssignment_3_0_2_0(), "rule__SolitaryFeature__GroupsAssignment_3_0_2_0");
					put(grammarAccess.getSolitaryFeatureAccess().getGroupsAssignment_3_0_2_1(), "rule__SolitaryFeature__GroupsAssignment_3_0_2_1");
					put(grammarAccess.getSolitaryFeatureAccess().getFeaturesAssignment_3_0_3_0(), "rule__SolitaryFeature__FeaturesAssignment_3_0_3_0");
					put(grammarAccess.getSolitaryFeatureAccess().getFeaturesAssignment_3_0_3_1(), "rule__SolitaryFeature__FeaturesAssignment_3_0_3_1");
					put(grammarAccess.getSolitaryFeatureAccess().getConstraintsAssignment_3_0_4_1(), "rule__SolitaryFeature__ConstraintsAssignment_3_0_4_1");
					put(grammarAccess.getSolitaryFeatureAccess().getConstraintsAssignment_3_0_4_2_1(), "rule__SolitaryFeature__ConstraintsAssignment_3_0_4_2_1");
					put(grammarAccess.getSolitaryFeatureAccess().getConstraintsAssignment_3_1_1(), "rule__SolitaryFeature__ConstraintsAssignment_3_1_1");
					put(grammarAccess.getGroupAccess().getInclusiveAssignment_0(), "rule__Group__InclusiveAssignment_0");
					put(grammarAccess.getGroupAccess().getGroupedFeaturesAssignment_2(), "rule__Group__GroupedFeaturesAssignment_2");
					put(grammarAccess.getGroupAccess().getGroupedFeaturesAssignment_3(), "rule__Group__GroupedFeaturesAssignment_3");
					put(grammarAccess.getGroupedFeatureAccess().getNameAssignment_1(), "rule__GroupedFeature__NameAssignment_1");
					put(grammarAccess.getGroupedFeatureAccess().getTypeAssignment_2_0_1_1(), "rule__GroupedFeature__TypeAssignment_2_0_1_1");
					put(grammarAccess.getGroupedFeatureAccess().getGroupsAssignment_2_0_2_2(), "rule__GroupedFeature__GroupsAssignment_2_0_2_2");
					put(grammarAccess.getGroupedFeatureAccess().getGroupsAssignment_2_0_2_3_1(), "rule__GroupedFeature__GroupsAssignment_2_0_2_3_1");
					put(grammarAccess.getGroupedFeatureAccess().getFeaturesAssignment_2_0_3_0(), "rule__GroupedFeature__FeaturesAssignment_2_0_3_0");
					put(grammarAccess.getGroupedFeatureAccess().getFeaturesAssignment_2_0_3_1_1(), "rule__GroupedFeature__FeaturesAssignment_2_0_3_1_1");
					put(grammarAccess.getGroupedFeatureAccess().getConstraintsAssignment_2_0_4_2(), "rule__GroupedFeature__ConstraintsAssignment_2_0_4_2");
					put(grammarAccess.getGroupedFeatureAccess().getConstraintsAssignment_2_0_4_3_1(), "rule__GroupedFeature__ConstraintsAssignment_2_0_4_3_1");
					put(grammarAccess.getGroupedFeatureAccess().getConstraintsAssignment_2_1_1(), "rule__GroupedFeature__ConstraintsAssignment_2_1_1");
					put(grammarAccess.getBinaryOperationAccess().getOperatorAssignment_3(), "rule__BinaryOperation__OperatorAssignment_3");
					put(grammarAccess.getBinaryOperationAccess().getRexpAssignment_5(), "rule__BinaryOperation__RexpAssignment_5");
					put(grammarAccess.getBinaryOperationAccess().getLexpAssignment_7(), "rule__BinaryOperation__LexpAssignment_7");
					put(grammarAccess.getUnaryOperationAccess().getOperatorAssignment_3(), "rule__UnaryOperation__OperatorAssignment_3");
					put(grammarAccess.getUnaryOperationAccess().getExpAssignment_5(), "rule__UnaryOperation__ExpAssignment_5");
					put(grammarAccess.getNumberAccess().getValueAssignment(), "rule__Number__ValueAssignment");
					put(grammarAccess.getIdentifierAccess().getNameAssignment_1(), "rule__Identifier__NameAssignment_1");
					put(grammarAccess.getIdentifierAccess().getRefAssignment_4(), "rule__Identifier__RefAssignment_4");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.example.mydsl1.ui.contentassist.antlr.internal.InternalMyDslParser typedParser = (org.xtext.example.mydsl1.ui.contentassist.antlr.internal.InternalMyDslParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
