/*
* generated by Xtext
*/
package org.xtext.example.mydsl1.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class MyDslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cModelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cRootKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cRootFeatureAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cRootFeatureFeatureParserRuleCall_3_1_0 = (RuleCall)cRootFeatureAssignment_3_1.eContents().get(0);
		private final Group cGroup_3_2 = (Group)cGroup_3.eContents().get(2);
		private final Keyword cRootKeyword_3_2_0 = (Keyword)cGroup_3_2.eContents().get(0);
		private final Assignment cRootFeatureAssignment_3_2_1 = (Assignment)cGroup_3_2.eContents().get(1);
		private final RuleCall cRootFeatureFeatureParserRuleCall_3_2_1_0 = (RuleCall)cRootFeatureAssignment_3_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Model:
		//	{Model} "Model" "{" ("Root" RootFeature+=Feature ("Root" RootFeature+=Feature)*)? "}";
		public ParserRule getRule() { return rule; }

		//{Model} "Model" "{" ("Root" RootFeature+=Feature ("Root" RootFeature+=Feature)*)? "}"
		public Group getGroup() { return cGroup; }

		//{Model}
		public Action getModelAction_0() { return cModelAction_0; }

		//"Model"
		public Keyword getModelKeyword_1() { return cModelKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("Root" RootFeature+=Feature ("Root" RootFeature+=Feature)*)?
		public Group getGroup_3() { return cGroup_3; }

		//"Root"
		public Keyword getRootKeyword_3_0() { return cRootKeyword_3_0; }

		//RootFeature+=Feature
		public Assignment getRootFeatureAssignment_3_1() { return cRootFeatureAssignment_3_1; }

		//Feature
		public RuleCall getRootFeatureFeatureParserRuleCall_3_1_0() { return cRootFeatureFeatureParserRuleCall_3_1_0; }

		//("Root" RootFeature+=Feature)*
		public Group getGroup_3_2() { return cGroup_3_2; }

		//"Root"
		public Keyword getRootKeyword_3_2_0() { return cRootKeyword_3_2_0; }

		//RootFeature+=Feature
		public Assignment getRootFeatureAssignment_3_2_1() { return cRootFeatureAssignment_3_2_1; }

		//Feature
		public RuleCall getRootFeatureFeatureParserRuleCall_3_2_1_0() { return cRootFeatureFeatureParserRuleCall_3_2_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class FeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Feature");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSolitaryFeatureParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cGroupedFeatureParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Feature:
		//	SolitaryFeature | GroupedFeature;
		public ParserRule getRule() { return rule; }

		//SolitaryFeature | GroupedFeature
		public Alternatives getAlternatives() { return cAlternatives; }

		//SolitaryFeature
		public RuleCall getSolitaryFeatureParserRuleCall_0() { return cSolitaryFeatureParserRuleCall_0; }

		//GroupedFeature
		public RuleCall getGroupedFeatureParserRuleCall_1() { return cGroupedFeatureParserRuleCall_1; }
	}

	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Expression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cBinaryOperationParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cUnaryOperationParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cNULLParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cNumberParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cIdentifierParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//Expression:
		//	BinaryOperation | UnaryOperation | NULL | Number | Identifier;
		public ParserRule getRule() { return rule; }

		//BinaryOperation | UnaryOperation | NULL | Number | Identifier
		public Alternatives getAlternatives() { return cAlternatives; }

		//BinaryOperation
		public RuleCall getBinaryOperationParserRuleCall_0() { return cBinaryOperationParserRuleCall_0; }

		//UnaryOperation
		public RuleCall getUnaryOperationParserRuleCall_1() { return cUnaryOperationParserRuleCall_1; }

		//NULL
		public RuleCall getNULLParserRuleCall_2() { return cNULLParserRuleCall_2; }

		//Number
		public RuleCall getNumberParserRuleCall_3() { return cNumberParserRuleCall_3; }

		//Identifier
		public RuleCall getIdentifierParserRuleCall_4() { return cIdentifierParserRuleCall_4; }
	}

	public class SolitaryFeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SolitaryFeature");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFeatureKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cRequiredAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cRequiredSolitaryTypeEnumRuleCall_1_0 = (RuleCall)cRequiredAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Group cGroup_3_0 = (Group)cAlternatives_3.eContents().get(0);
		private final Keyword cEqualsSignGreaterThanSignKeyword_3_0_0 = (Keyword)cGroup_3_0.eContents().get(0);
		private final Group cGroup_3_0_1 = (Group)cGroup_3_0.eContents().get(1);
		private final Keyword cTypeKeyword_3_0_1_0 = (Keyword)cGroup_3_0_1.eContents().get(0);
		private final Assignment cTypeAssignment_3_0_1_1 = (Assignment)cGroup_3_0_1.eContents().get(1);
		private final RuleCall cTypeSimpleTypeEnumRuleCall_3_0_1_1_0 = (RuleCall)cTypeAssignment_3_0_1_1.eContents().get(0);
		private final Group cGroup_3_0_2 = (Group)cGroup_3_0.eContents().get(2);
		private final Assignment cGroupsAssignment_3_0_2_0 = (Assignment)cGroup_3_0_2.eContents().get(0);
		private final RuleCall cGroupsGroupParserRuleCall_3_0_2_0_0 = (RuleCall)cGroupsAssignment_3_0_2_0.eContents().get(0);
		private final Assignment cGroupsAssignment_3_0_2_1 = (Assignment)cGroup_3_0_2.eContents().get(1);
		private final RuleCall cGroupsGroupParserRuleCall_3_0_2_1_0 = (RuleCall)cGroupsAssignment_3_0_2_1.eContents().get(0);
		private final Group cGroup_3_0_3 = (Group)cGroup_3_0.eContents().get(3);
		private final Assignment cFeaturesAssignment_3_0_3_0 = (Assignment)cGroup_3_0_3.eContents().get(0);
		private final RuleCall cFeaturesSolitaryFeatureParserRuleCall_3_0_3_0_0 = (RuleCall)cFeaturesAssignment_3_0_3_0.eContents().get(0);
		private final Assignment cFeaturesAssignment_3_0_3_1 = (Assignment)cGroup_3_0_3.eContents().get(1);
		private final RuleCall cFeaturesSolitaryFeatureParserRuleCall_3_0_3_1_0 = (RuleCall)cFeaturesAssignment_3_0_3_1.eContents().get(0);
		private final Group cGroup_3_0_4 = (Group)cGroup_3_0.eContents().get(4);
		private final Keyword cNumberSignKeyword_3_0_4_0 = (Keyword)cGroup_3_0_4.eContents().get(0);
		private final Assignment cConstraintsAssignment_3_0_4_1 = (Assignment)cGroup_3_0_4.eContents().get(1);
		private final RuleCall cConstraintsExpressionParserRuleCall_3_0_4_1_0 = (RuleCall)cConstraintsAssignment_3_0_4_1.eContents().get(0);
		private final Group cGroup_3_0_4_2 = (Group)cGroup_3_0_4.eContents().get(2);
		private final Keyword cCommaKeyword_3_0_4_2_0 = (Keyword)cGroup_3_0_4_2.eContents().get(0);
		private final Assignment cConstraintsAssignment_3_0_4_2_1 = (Assignment)cGroup_3_0_4_2.eContents().get(1);
		private final RuleCall cConstraintsExpressionParserRuleCall_3_0_4_2_1_0 = (RuleCall)cConstraintsAssignment_3_0_4_2_1.eContents().get(0);
		private final Keyword cNumberSignKeyword_3_0_4_3 = (Keyword)cGroup_3_0_4.eContents().get(3);
		private final Keyword cSemicolonKeyword_3_0_5 = (Keyword)cGroup_3_0.eContents().get(5);
		private final Group cGroup_3_1 = (Group)cAlternatives_3.eContents().get(1);
		private final Keyword cEqualsSignKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Assignment cConstraintsAssignment_3_1_1 = (Assignment)cGroup_3_1.eContents().get(1);
		private final RuleCall cConstraintsExpressionParserRuleCall_3_1_1_0 = (RuleCall)cConstraintsAssignment_3_1_1.eContents().get(0);
		
		//SolitaryFeature:
		//	"feature" required=SolitaryType? name=EString ("=>" ("type" type=SimpleType)? (groups+=Group groups+=Group*)?
		//	(features+=SolitaryFeature features+=SolitaryFeature*)? ("#" constraints+=Expression ("," constraints+=Expression)*
		//	"#")? ";" | "=" constraints+=Expression);
		public ParserRule getRule() { return rule; }

		//"feature" required=SolitaryType? name=EString ("=>" ("type" type=SimpleType)? (groups+=Group groups+=Group*)?
		//(features+=SolitaryFeature features+=SolitaryFeature*)? ("#" constraints+=Expression ("," constraints+=Expression)*
		//"#")? ";" | "=" constraints+=Expression)
		public Group getGroup() { return cGroup; }

		//"feature"
		public Keyword getFeatureKeyword_0() { return cFeatureKeyword_0; }

		//required=SolitaryType?
		public Assignment getRequiredAssignment_1() { return cRequiredAssignment_1; }

		//SolitaryType
		public RuleCall getRequiredSolitaryTypeEnumRuleCall_1_0() { return cRequiredSolitaryTypeEnumRuleCall_1_0; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"=>" ("type" type=SimpleType)? (groups+=Group groups+=Group*)? (features+=SolitaryFeature features+=SolitaryFeature*)?
		//("#" constraints+=Expression ("," constraints+=Expression)* "#")? ";" | "=" constraints+=Expression
		public Alternatives getAlternatives_3() { return cAlternatives_3; }

		//"=>" ("type" type=SimpleType)? (groups+=Group groups+=Group*)? (features+=SolitaryFeature features+=SolitaryFeature*)?
		//("#" constraints+=Expression ("," constraints+=Expression)* "#")? ";"
		public Group getGroup_3_0() { return cGroup_3_0; }

		//"=>"
		public Keyword getEqualsSignGreaterThanSignKeyword_3_0_0() { return cEqualsSignGreaterThanSignKeyword_3_0_0; }

		//("type" type=SimpleType)?
		public Group getGroup_3_0_1() { return cGroup_3_0_1; }

		//"type"
		public Keyword getTypeKeyword_3_0_1_0() { return cTypeKeyword_3_0_1_0; }

		//type=SimpleType
		public Assignment getTypeAssignment_3_0_1_1() { return cTypeAssignment_3_0_1_1; }

		//SimpleType
		public RuleCall getTypeSimpleTypeEnumRuleCall_3_0_1_1_0() { return cTypeSimpleTypeEnumRuleCall_3_0_1_1_0; }

		//(groups+=Group groups+=Group*)?
		public Group getGroup_3_0_2() { return cGroup_3_0_2; }

		//groups+=Group
		public Assignment getGroupsAssignment_3_0_2_0() { return cGroupsAssignment_3_0_2_0; }

		//Group
		public RuleCall getGroupsGroupParserRuleCall_3_0_2_0_0() { return cGroupsGroupParserRuleCall_3_0_2_0_0; }

		//groups+=Group*
		public Assignment getGroupsAssignment_3_0_2_1() { return cGroupsAssignment_3_0_2_1; }

		//Group
		public RuleCall getGroupsGroupParserRuleCall_3_0_2_1_0() { return cGroupsGroupParserRuleCall_3_0_2_1_0; }

		//(features+=SolitaryFeature features+=SolitaryFeature*)?
		public Group getGroup_3_0_3() { return cGroup_3_0_3; }

		//features+=SolitaryFeature
		public Assignment getFeaturesAssignment_3_0_3_0() { return cFeaturesAssignment_3_0_3_0; }

		//SolitaryFeature
		public RuleCall getFeaturesSolitaryFeatureParserRuleCall_3_0_3_0_0() { return cFeaturesSolitaryFeatureParserRuleCall_3_0_3_0_0; }

		//features+=SolitaryFeature*
		public Assignment getFeaturesAssignment_3_0_3_1() { return cFeaturesAssignment_3_0_3_1; }

		//SolitaryFeature
		public RuleCall getFeaturesSolitaryFeatureParserRuleCall_3_0_3_1_0() { return cFeaturesSolitaryFeatureParserRuleCall_3_0_3_1_0; }

		//("#" constraints+=Expression ("," constraints+=Expression)* "#")?
		public Group getGroup_3_0_4() { return cGroup_3_0_4; }

		//"#"
		public Keyword getNumberSignKeyword_3_0_4_0() { return cNumberSignKeyword_3_0_4_0; }

		//constraints+=Expression
		public Assignment getConstraintsAssignment_3_0_4_1() { return cConstraintsAssignment_3_0_4_1; }

		//Expression
		public RuleCall getConstraintsExpressionParserRuleCall_3_0_4_1_0() { return cConstraintsExpressionParserRuleCall_3_0_4_1_0; }

		//("," constraints+=Expression)*
		public Group getGroup_3_0_4_2() { return cGroup_3_0_4_2; }

		//","
		public Keyword getCommaKeyword_3_0_4_2_0() { return cCommaKeyword_3_0_4_2_0; }

		//constraints+=Expression
		public Assignment getConstraintsAssignment_3_0_4_2_1() { return cConstraintsAssignment_3_0_4_2_1; }

		//Expression
		public RuleCall getConstraintsExpressionParserRuleCall_3_0_4_2_1_0() { return cConstraintsExpressionParserRuleCall_3_0_4_2_1_0; }

		//"#"
		public Keyword getNumberSignKeyword_3_0_4_3() { return cNumberSignKeyword_3_0_4_3; }

		//";"
		public Keyword getSemicolonKeyword_3_0_5() { return cSemicolonKeyword_3_0_5; }

		//"=" constraints+=Expression
		public Group getGroup_3_1() { return cGroup_3_1; }

		//"="
		public Keyword getEqualsSignKeyword_3_1_0() { return cEqualsSignKeyword_3_1_0; }

		//constraints+=Expression
		public Assignment getConstraintsAssignment_3_1_1() { return cConstraintsAssignment_3_1_1; }

		//Expression
		public RuleCall getConstraintsExpressionParserRuleCall_3_1_1_0() { return cConstraintsExpressionParserRuleCall_3_1_1_0; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class GroupElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Group");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cInclusiveAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cInclusiveAnyKeyword_0_0 = (Keyword)cInclusiveAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignGreaterThanSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cGroupedFeaturesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cGroupedFeaturesGroupedFeatureParserRuleCall_2_0 = (RuleCall)cGroupedFeaturesAssignment_2.eContents().get(0);
		private final Assignment cGroupedFeaturesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cGroupedFeaturesGroupedFeatureParserRuleCall_3_0 = (RuleCall)cGroupedFeaturesAssignment_3.eContents().get(0);
		private final Keyword cSemicolonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Group:
		//	inclusive?="any"? "=>" groupedFeatures+=GroupedFeature groupedFeatures+=GroupedFeature* ";";
		public ParserRule getRule() { return rule; }

		//inclusive?="any"? "=>" groupedFeatures+=GroupedFeature groupedFeatures+=GroupedFeature* ";"
		public Group getGroup() { return cGroup; }

		//inclusive?="any"?
		public Assignment getInclusiveAssignment_0() { return cInclusiveAssignment_0; }

		//"any"
		public Keyword getInclusiveAnyKeyword_0_0() { return cInclusiveAnyKeyword_0_0; }

		//"=>"
		public Keyword getEqualsSignGreaterThanSignKeyword_1() { return cEqualsSignGreaterThanSignKeyword_1; }

		//groupedFeatures+=GroupedFeature
		public Assignment getGroupedFeaturesAssignment_2() { return cGroupedFeaturesAssignment_2; }

		//GroupedFeature
		public RuleCall getGroupedFeaturesGroupedFeatureParserRuleCall_2_0() { return cGroupedFeaturesGroupedFeatureParserRuleCall_2_0; }

		//groupedFeatures+=GroupedFeature*
		public Assignment getGroupedFeaturesAssignment_3() { return cGroupedFeaturesAssignment_3; }

		//GroupedFeature
		public RuleCall getGroupedFeaturesGroupedFeatureParserRuleCall_3_0() { return cGroupedFeaturesGroupedFeatureParserRuleCall_3_0; }

		//";"
		public Keyword getSemicolonKeyword_4() { return cSemicolonKeyword_4; }
	}

	public class GroupedFeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "GroupedFeature");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cGroupedFeatureAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Group cGroup_2_0 = (Group)cAlternatives_2.eContents().get(0);
		private final Keyword cEqualsSignGreaterThanSignKeyword_2_0_0 = (Keyword)cGroup_2_0.eContents().get(0);
		private final Group cGroup_2_0_1 = (Group)cGroup_2_0.eContents().get(1);
		private final Keyword cTypeKeyword_2_0_1_0 = (Keyword)cGroup_2_0_1.eContents().get(0);
		private final Assignment cTypeAssignment_2_0_1_1 = (Assignment)cGroup_2_0_1.eContents().get(1);
		private final RuleCall cTypeSimpleTypeEnumRuleCall_2_0_1_1_0 = (RuleCall)cTypeAssignment_2_0_1_1.eContents().get(0);
		private final Group cGroup_2_0_2 = (Group)cGroup_2_0.eContents().get(2);
		private final Keyword cGroupsKeyword_2_0_2_0 = (Keyword)cGroup_2_0_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2_0_2_1 = (Keyword)cGroup_2_0_2.eContents().get(1);
		private final Assignment cGroupsAssignment_2_0_2_2 = (Assignment)cGroup_2_0_2.eContents().get(2);
		private final RuleCall cGroupsGroupParserRuleCall_2_0_2_2_0 = (RuleCall)cGroupsAssignment_2_0_2_2.eContents().get(0);
		private final Group cGroup_2_0_2_3 = (Group)cGroup_2_0_2.eContents().get(3);
		private final Keyword cCommaKeyword_2_0_2_3_0 = (Keyword)cGroup_2_0_2_3.eContents().get(0);
		private final Assignment cGroupsAssignment_2_0_2_3_1 = (Assignment)cGroup_2_0_2_3.eContents().get(1);
		private final RuleCall cGroupsGroupParserRuleCall_2_0_2_3_1_0 = (RuleCall)cGroupsAssignment_2_0_2_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_0_2_4 = (Keyword)cGroup_2_0_2.eContents().get(4);
		private final Group cGroup_2_0_3 = (Group)cGroup_2_0.eContents().get(3);
		private final Assignment cFeaturesAssignment_2_0_3_0 = (Assignment)cGroup_2_0_3.eContents().get(0);
		private final RuleCall cFeaturesSolitaryFeatureParserRuleCall_2_0_3_0_0 = (RuleCall)cFeaturesAssignment_2_0_3_0.eContents().get(0);
		private final Group cGroup_2_0_3_1 = (Group)cGroup_2_0_3.eContents().get(1);
		private final Keyword cCommaKeyword_2_0_3_1_0 = (Keyword)cGroup_2_0_3_1.eContents().get(0);
		private final Assignment cFeaturesAssignment_2_0_3_1_1 = (Assignment)cGroup_2_0_3_1.eContents().get(1);
		private final RuleCall cFeaturesSolitaryFeatureParserRuleCall_2_0_3_1_1_0 = (RuleCall)cFeaturesAssignment_2_0_3_1_1.eContents().get(0);
		private final Group cGroup_2_0_4 = (Group)cGroup_2_0.eContents().get(4);
		private final Keyword cConstraintsKeyword_2_0_4_0 = (Keyword)cGroup_2_0_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2_0_4_1 = (Keyword)cGroup_2_0_4.eContents().get(1);
		private final Assignment cConstraintsAssignment_2_0_4_2 = (Assignment)cGroup_2_0_4.eContents().get(2);
		private final RuleCall cConstraintsExpressionParserRuleCall_2_0_4_2_0 = (RuleCall)cConstraintsAssignment_2_0_4_2.eContents().get(0);
		private final Group cGroup_2_0_4_3 = (Group)cGroup_2_0_4.eContents().get(3);
		private final Keyword cCommaKeyword_2_0_4_3_0 = (Keyword)cGroup_2_0_4_3.eContents().get(0);
		private final Assignment cConstraintsAssignment_2_0_4_3_1 = (Assignment)cGroup_2_0_4_3.eContents().get(1);
		private final RuleCall cConstraintsExpressionParserRuleCall_2_0_4_3_1_0 = (RuleCall)cConstraintsAssignment_2_0_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_0_4_4 = (Keyword)cGroup_2_0_4.eContents().get(4);
		private final Keyword cSemicolonKeyword_2_0_5 = (Keyword)cGroup_2_0.eContents().get(5);
		private final Group cGroup_2_1 = (Group)cAlternatives_2.eContents().get(1);
		private final Keyword cEqualsSignKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cConstraintsAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cConstraintsExpressionParserRuleCall_2_1_1_0 = (RuleCall)cConstraintsAssignment_2_1_1.eContents().get(0);
		
		//GroupedFeature:
		//	{GroupedFeature} name=EString ("=>" ("type" type=SimpleType)? ("groups" "{" groups+=Group ("," groups+=Group)* "}")?
		//	(features+=SolitaryFeature ("," features+=SolitaryFeature)*)? ("constraints" "{" constraints+=Expression (","
		//	constraints+=Expression)* "}")? ";" | "=" constraints+=Expression);
		public ParserRule getRule() { return rule; }

		//{GroupedFeature} name=EString ("=>" ("type" type=SimpleType)? ("groups" "{" groups+=Group ("," groups+=Group)* "}")?
		//(features+=SolitaryFeature ("," features+=SolitaryFeature)*)? ("constraints" "{" constraints+=Expression (","
		//constraints+=Expression)* "}")? ";" | "=" constraints+=Expression)
		public Group getGroup() { return cGroup; }

		//{GroupedFeature}
		public Action getGroupedFeatureAction_0() { return cGroupedFeatureAction_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"=>" ("type" type=SimpleType)? ("groups" "{" groups+=Group ("," groups+=Group)* "}")? (features+=SolitaryFeature (","
		//features+=SolitaryFeature)*)? ("constraints" "{" constraints+=Expression ("," constraints+=Expression)* "}")? ";" |
		//"=" constraints+=Expression
		public Alternatives getAlternatives_2() { return cAlternatives_2; }

		//"=>" ("type" type=SimpleType)? ("groups" "{" groups+=Group ("," groups+=Group)* "}")? (features+=SolitaryFeature (","
		//features+=SolitaryFeature)*)? ("constraints" "{" constraints+=Expression ("," constraints+=Expression)* "}")? ";"
		public Group getGroup_2_0() { return cGroup_2_0; }

		//"=>"
		public Keyword getEqualsSignGreaterThanSignKeyword_2_0_0() { return cEqualsSignGreaterThanSignKeyword_2_0_0; }

		//("type" type=SimpleType)?
		public Group getGroup_2_0_1() { return cGroup_2_0_1; }

		//"type"
		public Keyword getTypeKeyword_2_0_1_0() { return cTypeKeyword_2_0_1_0; }

		//type=SimpleType
		public Assignment getTypeAssignment_2_0_1_1() { return cTypeAssignment_2_0_1_1; }

		//SimpleType
		public RuleCall getTypeSimpleTypeEnumRuleCall_2_0_1_1_0() { return cTypeSimpleTypeEnumRuleCall_2_0_1_1_0; }

		//("groups" "{" groups+=Group ("," groups+=Group)* "}")?
		public Group getGroup_2_0_2() { return cGroup_2_0_2; }

		//"groups"
		public Keyword getGroupsKeyword_2_0_2_0() { return cGroupsKeyword_2_0_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2_0_2_1() { return cLeftCurlyBracketKeyword_2_0_2_1; }

		//groups+=Group
		public Assignment getGroupsAssignment_2_0_2_2() { return cGroupsAssignment_2_0_2_2; }

		//Group
		public RuleCall getGroupsGroupParserRuleCall_2_0_2_2_0() { return cGroupsGroupParserRuleCall_2_0_2_2_0; }

		//("," groups+=Group)*
		public Group getGroup_2_0_2_3() { return cGroup_2_0_2_3; }

		//","
		public Keyword getCommaKeyword_2_0_2_3_0() { return cCommaKeyword_2_0_2_3_0; }

		//groups+=Group
		public Assignment getGroupsAssignment_2_0_2_3_1() { return cGroupsAssignment_2_0_2_3_1; }

		//Group
		public RuleCall getGroupsGroupParserRuleCall_2_0_2_3_1_0() { return cGroupsGroupParserRuleCall_2_0_2_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_2_0_2_4() { return cRightCurlyBracketKeyword_2_0_2_4; }

		//(features+=SolitaryFeature ("," features+=SolitaryFeature)*)?
		public Group getGroup_2_0_3() { return cGroup_2_0_3; }

		//features+=SolitaryFeature
		public Assignment getFeaturesAssignment_2_0_3_0() { return cFeaturesAssignment_2_0_3_0; }

		//SolitaryFeature
		public RuleCall getFeaturesSolitaryFeatureParserRuleCall_2_0_3_0_0() { return cFeaturesSolitaryFeatureParserRuleCall_2_0_3_0_0; }

		//("," features+=SolitaryFeature)*
		public Group getGroup_2_0_3_1() { return cGroup_2_0_3_1; }

		//","
		public Keyword getCommaKeyword_2_0_3_1_0() { return cCommaKeyword_2_0_3_1_0; }

		//features+=SolitaryFeature
		public Assignment getFeaturesAssignment_2_0_3_1_1() { return cFeaturesAssignment_2_0_3_1_1; }

		//SolitaryFeature
		public RuleCall getFeaturesSolitaryFeatureParserRuleCall_2_0_3_1_1_0() { return cFeaturesSolitaryFeatureParserRuleCall_2_0_3_1_1_0; }

		//("constraints" "{" constraints+=Expression ("," constraints+=Expression)* "}")?
		public Group getGroup_2_0_4() { return cGroup_2_0_4; }

		//"constraints"
		public Keyword getConstraintsKeyword_2_0_4_0() { return cConstraintsKeyword_2_0_4_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2_0_4_1() { return cLeftCurlyBracketKeyword_2_0_4_1; }

		//constraints+=Expression
		public Assignment getConstraintsAssignment_2_0_4_2() { return cConstraintsAssignment_2_0_4_2; }

		//Expression
		public RuleCall getConstraintsExpressionParserRuleCall_2_0_4_2_0() { return cConstraintsExpressionParserRuleCall_2_0_4_2_0; }

		//("," constraints+=Expression)*
		public Group getGroup_2_0_4_3() { return cGroup_2_0_4_3; }

		//","
		public Keyword getCommaKeyword_2_0_4_3_0() { return cCommaKeyword_2_0_4_3_0; }

		//constraints+=Expression
		public Assignment getConstraintsAssignment_2_0_4_3_1() { return cConstraintsAssignment_2_0_4_3_1; }

		//Expression
		public RuleCall getConstraintsExpressionParserRuleCall_2_0_4_3_1_0() { return cConstraintsExpressionParserRuleCall_2_0_4_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_2_0_4_4() { return cRightCurlyBracketKeyword_2_0_4_4; }

		//";"
		public Keyword getSemicolonKeyword_2_0_5() { return cSemicolonKeyword_2_0_5; }

		//"=" constraints+=Expression
		public Group getGroup_2_1() { return cGroup_2_1; }

		//"="
		public Keyword getEqualsSignKeyword_2_1_0() { return cEqualsSignKeyword_2_1_0; }

		//constraints+=Expression
		public Assignment getConstraintsAssignment_2_1_1() { return cConstraintsAssignment_2_1_1; }

		//Expression
		public RuleCall getConstraintsExpressionParserRuleCall_2_1_1_0() { return cConstraintsExpressionParserRuleCall_2_1_1_0; }
	}

	public class BinaryOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BinaryOperation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBinaryOperationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cOperatorKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cOperatorAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cOperatorBinaryOperatorEnumRuleCall_3_0 = (RuleCall)cOperatorAssignment_3.eContents().get(0);
		private final Keyword cRexpKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cRexpAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cRexpExpressionParserRuleCall_5_0 = (RuleCall)cRexpAssignment_5.eContents().get(0);
		private final Keyword cLexpKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cLexpAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cLexpExpressionParserRuleCall_7_0 = (RuleCall)cLexpAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//BinaryOperation:
		//	"BinaryOperation" "{" "operator" operator=BinaryOperator "rexp" rexp=Expression "lexp" lexp=Expression "}";
		public ParserRule getRule() { return rule; }

		//"BinaryOperation" "{" "operator" operator=BinaryOperator "rexp" rexp=Expression "lexp" lexp=Expression "}"
		public Group getGroup() { return cGroup; }

		//"BinaryOperation"
		public Keyword getBinaryOperationKeyword_0() { return cBinaryOperationKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"operator"
		public Keyword getOperatorKeyword_2() { return cOperatorKeyword_2; }

		//operator=BinaryOperator
		public Assignment getOperatorAssignment_3() { return cOperatorAssignment_3; }

		//BinaryOperator
		public RuleCall getOperatorBinaryOperatorEnumRuleCall_3_0() { return cOperatorBinaryOperatorEnumRuleCall_3_0; }

		//"rexp"
		public Keyword getRexpKeyword_4() { return cRexpKeyword_4; }

		//rexp=Expression
		public Assignment getRexpAssignment_5() { return cRexpAssignment_5; }

		//Expression
		public RuleCall getRexpExpressionParserRuleCall_5_0() { return cRexpExpressionParserRuleCall_5_0; }

		//"lexp"
		public Keyword getLexpKeyword_6() { return cLexpKeyword_6; }

		//lexp=Expression
		public Assignment getLexpAssignment_7() { return cLexpAssignment_7; }

		//Expression
		public RuleCall getLexpExpressionParserRuleCall_7_0() { return cLexpExpressionParserRuleCall_7_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class UnaryOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "UnaryOperation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUnaryOperationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cOperatorKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cOperatorAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cOperatorUnaryOperatorEnumRuleCall_3_0 = (RuleCall)cOperatorAssignment_3.eContents().get(0);
		private final Keyword cExpKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cExpAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cExpExpressionParserRuleCall_5_0 = (RuleCall)cExpAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//UnaryOperation:
		//	"UnaryOperation" "{" "operator" operator=UnaryOperator "exp" exp=Expression "}";
		public ParserRule getRule() { return rule; }

		//"UnaryOperation" "{" "operator" operator=UnaryOperator "exp" exp=Expression "}"
		public Group getGroup() { return cGroup; }

		//"UnaryOperation"
		public Keyword getUnaryOperationKeyword_0() { return cUnaryOperationKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"operator"
		public Keyword getOperatorKeyword_2() { return cOperatorKeyword_2; }

		//operator=UnaryOperator
		public Assignment getOperatorAssignment_3() { return cOperatorAssignment_3; }

		//UnaryOperator
		public RuleCall getOperatorUnaryOperatorEnumRuleCall_3_0() { return cOperatorUnaryOperatorEnumRuleCall_3_0; }

		//"exp"
		public Keyword getExpKeyword_4() { return cExpKeyword_4; }

		//exp=Expression
		public Assignment getExpAssignment_5() { return cExpAssignment_5; }

		//Expression
		public RuleCall getExpExpressionParserRuleCall_5_0() { return cExpExpressionParserRuleCall_5_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class NULLElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "NULL");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cNULLAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cNULLKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//NULL:
		//	{NULL} "NULL";
		public ParserRule getRule() { return rule; }

		//{NULL} "NULL"
		public Group getGroup() { return cGroup; }

		//{NULL}
		public Action getNULLAction_0() { return cNULLAction_0; }

		//"NULL"
		public Keyword getNULLKeyword_1() { return cNULLKeyword_1; }
	}

	public class NumberElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Number");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueEIntParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//Number:
		//	value=EInt;
		public ParserRule getRule() { return rule; }

		//value=EInt
		public Assignment getValueAssignment() { return cValueAssignment; }

		//EInt
		public RuleCall getValueEIntParserRuleCall_0() { return cValueEIntParserRuleCall_0; }
	}

	public class IdentifierElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Identifier");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIdentifierKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cRefKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cRefAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cRefFeatureCrossReference_4_0 = (CrossReference)cRefAssignment_4.eContents().get(0);
		private final RuleCall cRefFeatureEStringParserRuleCall_4_0_1 = (RuleCall)cRefFeatureCrossReference_4_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Identifier:
		//	"Identifier" name=EString "{" "ref" ref=[Feature|EString] "}";
		public ParserRule getRule() { return rule; }

		//"Identifier" name=EString "{" "ref" ref=[Feature|EString] "}"
		public Group getGroup() { return cGroup; }

		//"Identifier"
		public Keyword getIdentifierKeyword_0() { return cIdentifierKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"ref"
		public Keyword getRefKeyword_3() { return cRefKeyword_3; }

		//ref=[Feature|EString]
		public Assignment getRefAssignment_4() { return cRefAssignment_4; }

		//[Feature|EString]
		public CrossReference getRefFeatureCrossReference_4_0() { return cRefFeatureCrossReference_4_0; }

		//EString
		public RuleCall getRefFeatureEStringParserRuleCall_4_0_1() { return cRefFeatureEStringParserRuleCall_4_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//	"-"? INT;
		public ParserRule getRule() { return rule; }

		//"-"? INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//	"true" | "false";
		public ParserRule getRule() { return rule; }

		//"true" | "false"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"true"
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }

		//"false"
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	
	
	public class BinaryOperatorElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "BinaryOperator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cEqualsEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cEqualsEqualsKeyword_0_0 = (Keyword)cEqualsEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cHigherEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cHigherHigherKeyword_1_0 = (Keyword)cHigherEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cLowerEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cLowerLowerKeyword_2_0 = (Keyword)cLowerEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cAndEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cAndAndKeyword_3_0 = (Keyword)cAndEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cAddEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cAddAddKeyword_4_0 = (Keyword)cAddEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cSubtractEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cSubtractSubtractKeyword_5_0 = (Keyword)cSubtractEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cDivideEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cDivideDivideKeyword_6_0 = (Keyword)cDivideEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cMultiplyEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cMultiplyMultiplyKeyword_7_0 = (Keyword)cMultiplyEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cOrEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cOrOrKeyword_8_0 = (Keyword)cOrEnumLiteralDeclaration_8.eContents().get(0);
		
		//enum BinaryOperator:
		//	Equals | Higher | Lower | And | Add | Subtract | Divide | Multiply | Or;
		public EnumRule getRule() { return rule; }

		//Equals | Higher | Lower | And | Add | Subtract | Divide | Multiply | Or
		public Alternatives getAlternatives() { return cAlternatives; }

		//Equals
		public EnumLiteralDeclaration getEqualsEnumLiteralDeclaration_0() { return cEqualsEnumLiteralDeclaration_0; }

		//"Equals"
		public Keyword getEqualsEqualsKeyword_0_0() { return cEqualsEqualsKeyword_0_0; }

		//Higher
		public EnumLiteralDeclaration getHigherEnumLiteralDeclaration_1() { return cHigherEnumLiteralDeclaration_1; }

		//"Higher"
		public Keyword getHigherHigherKeyword_1_0() { return cHigherHigherKeyword_1_0; }

		//Lower
		public EnumLiteralDeclaration getLowerEnumLiteralDeclaration_2() { return cLowerEnumLiteralDeclaration_2; }

		//"Lower"
		public Keyword getLowerLowerKeyword_2_0() { return cLowerLowerKeyword_2_0; }

		//And
		public EnumLiteralDeclaration getAndEnumLiteralDeclaration_3() { return cAndEnumLiteralDeclaration_3; }

		//"And"
		public Keyword getAndAndKeyword_3_0() { return cAndAndKeyword_3_0; }

		//Add
		public EnumLiteralDeclaration getAddEnumLiteralDeclaration_4() { return cAddEnumLiteralDeclaration_4; }

		//"Add"
		public Keyword getAddAddKeyword_4_0() { return cAddAddKeyword_4_0; }

		//Subtract
		public EnumLiteralDeclaration getSubtractEnumLiteralDeclaration_5() { return cSubtractEnumLiteralDeclaration_5; }

		//"Subtract"
		public Keyword getSubtractSubtractKeyword_5_0() { return cSubtractSubtractKeyword_5_0; }

		//Divide
		public EnumLiteralDeclaration getDivideEnumLiteralDeclaration_6() { return cDivideEnumLiteralDeclaration_6; }

		//"Divide"
		public Keyword getDivideDivideKeyword_6_0() { return cDivideDivideKeyword_6_0; }

		//Multiply
		public EnumLiteralDeclaration getMultiplyEnumLiteralDeclaration_7() { return cMultiplyEnumLiteralDeclaration_7; }

		//"Multiply"
		public Keyword getMultiplyMultiplyKeyword_7_0() { return cMultiplyMultiplyKeyword_7_0; }

		//Or
		public EnumLiteralDeclaration getOrEnumLiteralDeclaration_8() { return cOrEnumLiteralDeclaration_8; }

		//"Or"
		public Keyword getOrOrKeyword_8_0() { return cOrOrKeyword_8_0; }
	}

	public class UnaryOperatorElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "UnaryOperator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cNotEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cNotNotKeyword_0_0 = (Keyword)cNotEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cMinusEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cMinusMinusKeyword_1_0 = (Keyword)cMinusEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum UnaryOperator:
		//	Not | Minus;
		public EnumRule getRule() { return rule; }

		//Not | Minus
		public Alternatives getAlternatives() { return cAlternatives; }

		//Not
		public EnumLiteralDeclaration getNotEnumLiteralDeclaration_0() { return cNotEnumLiteralDeclaration_0; }

		//"Not"
		public Keyword getNotNotKeyword_0_0() { return cNotNotKeyword_0_0; }

		//Minus
		public EnumLiteralDeclaration getMinusEnumLiteralDeclaration_1() { return cMinusEnumLiteralDeclaration_1; }

		//"Minus"
		public Keyword getMinusMinusKeyword_1_0() { return cMinusMinusKeyword_1_0; }
	}

	public class SimpleTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "SimpleType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cBooleanEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cBooleanBooleanKeyword_0_0 = (Keyword)cBooleanEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cIntEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cIntIntKeyword_1_0 = (Keyword)cIntEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cDoubleEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cDoubleDoubleKeyword_2_0 = (Keyword)cDoubleEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cStringEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cStringStringKeyword_3_0 = (Keyword)cStringEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum SimpleType:
		//	boolean | int | double | String;
		public EnumRule getRule() { return rule; }

		//boolean | int | double | String
		public Alternatives getAlternatives() { return cAlternatives; }

		//boolean
		public EnumLiteralDeclaration getBooleanEnumLiteralDeclaration_0() { return cBooleanEnumLiteralDeclaration_0; }

		//"boolean"
		public Keyword getBooleanBooleanKeyword_0_0() { return cBooleanBooleanKeyword_0_0; }

		//int
		public EnumLiteralDeclaration getIntEnumLiteralDeclaration_1() { return cIntEnumLiteralDeclaration_1; }

		//"int"
		public Keyword getIntIntKeyword_1_0() { return cIntIntKeyword_1_0; }

		//double
		public EnumLiteralDeclaration getDoubleEnumLiteralDeclaration_2() { return cDoubleEnumLiteralDeclaration_2; }

		//"double"
		public Keyword getDoubleDoubleKeyword_2_0() { return cDoubleDoubleKeyword_2_0; }

		//String
		public EnumLiteralDeclaration getStringEnumLiteralDeclaration_3() { return cStringEnumLiteralDeclaration_3; }

		//"String"
		public Keyword getStringStringKeyword_3_0() { return cStringStringKeyword_3_0; }
	}

	public class SolitaryTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "SolitaryType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cOptionalEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cOptionalOptionalKeyword_0_0 = (Keyword)cOptionalEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cMandatoryEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cMandatoryMandatoryKeyword_1_0 = (Keyword)cMandatoryEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum SolitaryType:
		//	Optional | Mandatory;
		public EnumRule getRule() { return rule; }

		//Optional | Mandatory
		public Alternatives getAlternatives() { return cAlternatives; }

		//Optional
		public EnumLiteralDeclaration getOptionalEnumLiteralDeclaration_0() { return cOptionalEnumLiteralDeclaration_0; }

		//"Optional"
		public Keyword getOptionalOptionalKeyword_0_0() { return cOptionalOptionalKeyword_0_0; }

		//Mandatory
		public EnumLiteralDeclaration getMandatoryEnumLiteralDeclaration_1() { return cMandatoryEnumLiteralDeclaration_1; }

		//"Mandatory"
		public Keyword getMandatoryMandatoryKeyword_1_0() { return cMandatoryMandatoryKeyword_1_0; }
	}
	
	private ModelElements pModel;
	private FeatureElements pFeature;
	private ExpressionElements pExpression;
	private SolitaryFeatureElements pSolitaryFeature;
	private EStringElements pEString;
	private GroupElements pGroup;
	private GroupedFeatureElements pGroupedFeature;
	private BinaryOperationElements pBinaryOperation;
	private UnaryOperationElements pUnaryOperation;
	private NULLElements pNULL;
	private NumberElements pNumber;
	private IdentifierElements pIdentifier;
	private BinaryOperatorElements unknownRuleBinaryOperator;
	private UnaryOperatorElements unknownRuleUnaryOperator;
	private EIntElements pEInt;
	private EBooleanElements pEBoolean;
	private SimpleTypeElements unknownRuleSimpleType;
	private SolitaryTypeElements unknownRuleSolitaryType;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl1.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	{Model} "Model" "{" ("Root" RootFeature+=Feature ("Root" RootFeature+=Feature)*)? "}";
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//Feature:
	//	SolitaryFeature | GroupedFeature;
	public FeatureElements getFeatureAccess() {
		return (pFeature != null) ? pFeature : (pFeature = new FeatureElements());
	}
	
	public ParserRule getFeatureRule() {
		return getFeatureAccess().getRule();
	}

	//Expression:
	//	BinaryOperation | UnaryOperation | NULL | Number | Identifier;
	public ExpressionElements getExpressionAccess() {
		return (pExpression != null) ? pExpression : (pExpression = new ExpressionElements());
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}

	//SolitaryFeature:
	//	"feature" required=SolitaryType? name=EString ("=>" ("type" type=SimpleType)? (groups+=Group groups+=Group*)?
	//	(features+=SolitaryFeature features+=SolitaryFeature*)? ("#" constraints+=Expression ("," constraints+=Expression)*
	//	"#")? ";" | "=" constraints+=Expression);
	public SolitaryFeatureElements getSolitaryFeatureAccess() {
		return (pSolitaryFeature != null) ? pSolitaryFeature : (pSolitaryFeature = new SolitaryFeatureElements());
	}
	
	public ParserRule getSolitaryFeatureRule() {
		return getSolitaryFeatureAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return (pEString != null) ? pEString : (pEString = new EStringElements());
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//Group:
	//	inclusive?="any"? "=>" groupedFeatures+=GroupedFeature groupedFeatures+=GroupedFeature* ";";
	public GroupElements getGroupAccess() {
		return (pGroup != null) ? pGroup : (pGroup = new GroupElements());
	}
	
	public ParserRule getGroupRule() {
		return getGroupAccess().getRule();
	}

	//GroupedFeature:
	//	{GroupedFeature} name=EString ("=>" ("type" type=SimpleType)? ("groups" "{" groups+=Group ("," groups+=Group)* "}")?
	//	(features+=SolitaryFeature ("," features+=SolitaryFeature)*)? ("constraints" "{" constraints+=Expression (","
	//	constraints+=Expression)* "}")? ";" | "=" constraints+=Expression);
	public GroupedFeatureElements getGroupedFeatureAccess() {
		return (pGroupedFeature != null) ? pGroupedFeature : (pGroupedFeature = new GroupedFeatureElements());
	}
	
	public ParserRule getGroupedFeatureRule() {
		return getGroupedFeatureAccess().getRule();
	}

	//BinaryOperation:
	//	"BinaryOperation" "{" "operator" operator=BinaryOperator "rexp" rexp=Expression "lexp" lexp=Expression "}";
	public BinaryOperationElements getBinaryOperationAccess() {
		return (pBinaryOperation != null) ? pBinaryOperation : (pBinaryOperation = new BinaryOperationElements());
	}
	
	public ParserRule getBinaryOperationRule() {
		return getBinaryOperationAccess().getRule();
	}

	//UnaryOperation:
	//	"UnaryOperation" "{" "operator" operator=UnaryOperator "exp" exp=Expression "}";
	public UnaryOperationElements getUnaryOperationAccess() {
		return (pUnaryOperation != null) ? pUnaryOperation : (pUnaryOperation = new UnaryOperationElements());
	}
	
	public ParserRule getUnaryOperationRule() {
		return getUnaryOperationAccess().getRule();
	}

	//NULL:
	//	{NULL} "NULL";
	public NULLElements getNULLAccess() {
		return (pNULL != null) ? pNULL : (pNULL = new NULLElements());
	}
	
	public ParserRule getNULLRule() {
		return getNULLAccess().getRule();
	}

	//Number:
	//	value=EInt;
	public NumberElements getNumberAccess() {
		return (pNumber != null) ? pNumber : (pNumber = new NumberElements());
	}
	
	public ParserRule getNumberRule() {
		return getNumberAccess().getRule();
	}

	//Identifier:
	//	"Identifier" name=EString "{" "ref" ref=[Feature|EString] "}";
	public IdentifierElements getIdentifierAccess() {
		return (pIdentifier != null) ? pIdentifier : (pIdentifier = new IdentifierElements());
	}
	
	public ParserRule getIdentifierRule() {
		return getIdentifierAccess().getRule();
	}

	//enum BinaryOperator:
	//	Equals | Higher | Lower | And | Add | Subtract | Divide | Multiply | Or;
	public BinaryOperatorElements getBinaryOperatorAccess() {
		return (unknownRuleBinaryOperator != null) ? unknownRuleBinaryOperator : (unknownRuleBinaryOperator = new BinaryOperatorElements());
	}
	
	public EnumRule getBinaryOperatorRule() {
		return getBinaryOperatorAccess().getRule();
	}

	//enum UnaryOperator:
	//	Not | Minus;
	public UnaryOperatorElements getUnaryOperatorAccess() {
		return (unknownRuleUnaryOperator != null) ? unknownRuleUnaryOperator : (unknownRuleUnaryOperator = new UnaryOperatorElements());
	}
	
	public EnumRule getUnaryOperatorRule() {
		return getUnaryOperatorAccess().getRule();
	}

	//EInt returns ecore::EInt:
	//	"-"? INT;
	public EIntElements getEIntAccess() {
		return (pEInt != null) ? pEInt : (pEInt = new EIntElements());
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}

	//EBoolean returns ecore::EBoolean:
	//	"true" | "false";
	public EBooleanElements getEBooleanAccess() {
		return (pEBoolean != null) ? pEBoolean : (pEBoolean = new EBooleanElements());
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}

	//enum SimpleType:
	//	boolean | int | double | String;
	public SimpleTypeElements getSimpleTypeAccess() {
		return (unknownRuleSimpleType != null) ? unknownRuleSimpleType : (unknownRuleSimpleType = new SimpleTypeElements());
	}
	
	public EnumRule getSimpleTypeRule() {
		return getSimpleTypeAccess().getRule();
	}

	//enum SolitaryType:
	//	Optional | Mandatory;
	public SolitaryTypeElements getSolitaryTypeAccess() {
		return (unknownRuleSolitaryType != null) ? unknownRuleSolitaryType : (unknownRuleSolitaryType = new SolitaryTypeElements());
	}
	
	public EnumRule getSolitaryTypeRule() {
		return getSolitaryTypeAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
